type App {
  id: ID!
  name: String!
  url: String!
  updatedAt: String!
  createdAt: String!
}

type Chatbot {
  id: ID!
  app: App!
  apiKey: String!
  createdAt: String!
  updatedAt: String!
}

type KeyValueOutput {
  key: String!
  value: String!
}

type Webhook {
  id: ID!
  app: App!
  name: String!
  url: String!
  token: String!
  headers: [KeyValueOutput!]
  isActive: Boolean!
  createdAt: String!
  updatedAt: String!
}

type Ingestion {
  id: ID!
  app: App!
  name: String!
  apiKey: String!
  isActive: Boolean!
  createdAt: String!
  updatedAt: String!
}
