spring.application.name=app_service

# Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

# Redis
spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.cache.redis.time-to-live=${SPRING_REDIS_TTL:600000}

# Variables
auth-service.url=${AUTH_SERVICE_URL}

# GraphQL
spring.graphql.graphiql.enabled=${GRAPHQL_GRAPHIQL_ENABLED:false}
spring.graphql.graphiql.path=${GRAPHQL_GRAPHIQL_PATH:/graphiql}

# Custom variables
secrets.x-app-secret=${X_APP_SECRET:3FA97C7653BFF4FE4123DFCBCB479}
