type Query {
  getApps: [App]
  getChatbot(appId: String!): Chatbot
  getWebhook(appId: String!, webhookId: String!): Webhook
  getWebhooks(appId: String!): [Webhook]
  getIngestionAPIs(appId: String!): [Ingestion]
  getIngestionAPI(appId: String!, ingestionId: String!): Ingestion
}

type Mutation {
  createApp(input: CreateAppInput!): App
  createChatbot(appId: String!): Chatbot
  deleteChatbot(appId: ID!): App
  createWebhook(input: CreateWebhookInput!): Webhook
  deleteWebhook(webhookId: ID!, appId: ID!): Webhook
  updateWebhookActiveStatus(
    webhookId: ID!
    appId: ID!
    active: Boolean!
  ): Webhook
  createIngestionAPI(appId: String!, name: String!): Ingestion
  deleteIngestionAPI(ingestionAPIId: ID!, appId: ID!): Ingestion
  updateIngestionAPIActiveStatus(
    ingestionAPIId: ID!
    appId: ID!
    active: Boolean!
  ): Ingestion
}
