spring.application.name=bot-service

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:bot-service-group}

# Custom variables
secrets.x-app-secret=${X_APP_SECRET:3FA97C7653BFF4FE4123DFCBCB479}

# App service URL
app.service.url=${APP_SERVICE_URL}
