#Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=bot-service

#Custom variables
secrets.x-app-secret=3FA97C7653BFF4FE4123DFCBCB479

app.service.url=http://localhost:8082